### ISSUE TITLE
Define Poppler as a dependency

### ISSUE THREAD

**Issue by nagromc** [bastienlc/pdf-watermark#3]
Finally the project I was looking for! Simple & straightforward. I love it. Thanks for that.

When using the `--save-as-image` option, a huge traceback was printed, and at the very bottom, the following message was shown: `Is poppler installed and in PATH?`.

Please consider one of the following suggestions:
- adding a dependency section in `README.md` mentioning Poppler, with a link to the official website
- catch the exception thrown by pdf2image nicely

**Comment by bastienlc** [comment]
Thanks for the heads up, I added both. Unfortunately there aren't many projects to convert a PDF to an image without external dependencies, except [PyMuPDF](https://github.com/pymupdf/PyMuPDF) but using it would require switching from an MIT license to an AGPL one.
