### ISSUE TITLE
Working with different page formats

### ISSUE THREAD

**Issue by adoktr** [bastienlc/pdf-watermark#5]
Hello, I appreciate the cool code. I tried it in my tasks, I really liked its work. But there are tasks with PDF files, where pages of different sizes are mixed together (for example, one file consists of pages A4, A3, A1), this is where the code cannot cope.

**Comment by adoktr** [comment]
[test_output.pdf](https://github.com/bastienlc/pdf-watermark/files/14980382/test_output.pdf)

**Comment by bastienlc** [comment]
Hi, thanks for the suggestion, I'll add support for PDF with different page sizes soon.

**Comment by adoktr** [comment]
Hi, using the image as a watermark worked very well. True, the output does not have enough compression to reduce the file size, but this will delay processing. Great code. Thanks for the new functionality and code update.
[test.pdf](https://github.com/bastienlc/pdf-watermark/files/15094825/test.pdf)
